#!/usr/bin/env bash 

# Script to install all the tools needed to use the back end of PIN

sudo apt update
sudo apt -y install wget
sudo pip install py3dns
sudo pip install jwt
sudo pip install bcrypt
sudo pip install beautifulsoup4
sudo pip install selenium
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update
sudo apt-get install google-chrome-stable
sudo pip install lxml
sudo pip install requests
wget https://repo.mysql.com//mysql-apt-config_0.8.22-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.22-1_all.deb
sudo pip install mysql-connector-python
sudo apt install mysql-server
sudo apt install libmysqlclient-dev
sudo pip install flask-login
sudo pip install flask-mysqldb
sudo pip install flask-WTF
sudo pip install Babel